tasks:
  - name: Init dev tools 
    before: |
      npm install --location=global npm@latest typescript@latest
    init: |
      npm install
    command: npm run dev
  - name: Terminal
    openMode: split-right
gitConfig:
  alias.st: status
  alias.co: checkout
vscode:
  extensions:
    - usernamehw.errorlens
    - dbaeumer.vscode-eslint
    - medo64.render-crlf