name: Trigger CMS deploy to Stage
run-name: Trigger CMS deploy to Stage
on:
  workflow_dispatch:

jobs:
  trigger:
    name: Trigger CMS deploy to Stage
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CMS deploy to Stage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          WORKFLOW: deploy.yml
          ENVIRONMENT: stage
        run: |
          curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$REPOSITORY/actions/workflows/$WORKFLOW/dispatches \
              -d '{"ref":"main", "inputs": {"environment": "'"$ENVIRONMENT"'"}}'