name: Trigger CMS deploy to Production
run-name: Trigger CMS deploy to Production
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to production
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets:
      SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
