name: Trigger CMS deploy to Stage
run-name: Trigger CMS deploy to Stage
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to stage
    uses: ./.github/workflows/deploy.yml
    with:
      environment: stage
    secrets:
      SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
